### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by lionsandmersea** [paradigmnomad/SVO#8]
I am missing these files:
'Characters\Pam\Overlay\Pam_spring_Indoor_Sun.png'
'Characters\Pam\Overlay\Pam_spring_Outdoor_Sun.png'
The last time I downloaded this, Mari's Hospital sprites and portraits were missing, but I redownloaded it later and now have it. Would this be a quirk of how big the mod is? I don't know what other character sprites I may be missing in other seasons, because I haven't tested that.
Also, there seems to be random places where it works. For example, Vincent's sprite and portrait are the original images, but on the calendar, you're version shows for his birthday.

**Comment by paradigmnomad** [comment]
The missing Pam Overlay files should be resolved in 2.1.9.

In regards to the missing other files it is very possible that due to the size of the DL and how many individual files are in there they might not be downloaded properly. The only solution I would have for that would to be to redownload the file. For the sprites not changing on the calendar that would also be something I have no idea how to fix because the game automatically generates those.
